// 11 players for Argentina with respecive key-values

let Argentina = [
  {
    Name: "Willy Caballero",
    Position: "Goalkeeper",
    DOB: "09/28/1981",
    ZodiacSign: "Libra",
    JerseyNumber: "13",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p20310.png",
  },

  {
    Name: "Nicolas Tagliafico",
    Position: "Defender",
    DOB: "08/31/1992",
    ZodiacSign: "Virgo",
    JerseyNumber: "3",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture: "https://i.ytimg.com/vi/H9REk2OSLPM/maxresdefault.jpg",
  },
  {
    Name: "Federico Fazio",
    Position: "Defender",
    DOB: "03/17/1987",
    ZodiacSign: "Pisces",
    JerseyNumber: "20",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://worldcup.sportmatch.com/images/web/players/argentina/federico-fazio.jpg",
  },
  {
    Name: "Nicolas Otamendi",
    Position: "Defender",
    DOB: "02/12/1988",
    ZodiacSign: "Aquarius",
    JerseyNumber: "17",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://m.media-amazon.com/images/M/MV5BMWQxZWI0N2ItZGMzMy00N2Y1LThlNTYtZDFjOGVlODg1ZDhlXkEyXkFqcGdeQXVyODEyMTAwMDI@._V1_UY317_CR27,0,214,317_AL_.jpg",
  },
  {
    Name: "Gabriel Mercado",
    Position: "Defender",
    DOB: "03/18/1987",
    ZodiacSign: "Pisces",
    JerseyNumber: "25",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/86403.jpg",
  },
  {
    Name: "Angel Di Maria",
    Position: "Midfielder",
    DOB: "02/14/1988",
    ZodiacSign: "Aquarius",
    JerseyNumber: "11",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/NIG-ARG_%285%29.jpg",
  },
  {
    Name: "Javier Mascherano",
    Position: "Midfielder",
    DOB: "06/08/2984",
    ZodiacSign: "Gemini",
    JerseyNumber: "27",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://i.pinimg.com/originals/41/ae/2e/41ae2ee0e1d18da2bb41457ff985a961.jpg",
  },
  {
    Name: "Giovani Lo Celso",
    Position: "Midfielder",
    DOB: "04/09/1996",
    ZodiacSign: "Aries",
    JerseyNumber: "20",
    JerseyColor: "White",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://cdn.vox-cdn.com/thumbor/QVclgsN3Y4tmLZ1GdCaZVpPZDe4=/0x0:3185x4713/1200x800/filters:focal(1234x914:1742x1422)/cdn.vox-cdn.com/uploads/chorus_image/image/66203664/1160323486.jpg.0.jpg",
  },
  {
    Name: "Paulo Dybala",
    Position: "Midfielder",
    DOB: "11/15/1993",
    ZodiacSign: "Scorpio",
    JerseyNumber: "21",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://sportshub.cbsistatic.com/i/r/2020/04/29/fd8c07c3-7352-4094-806c-521bed164122/thumbnail/1200x675/3fcede754cb41c7a968b3e448c924fa9/paulo-dybala-juventus.jpg",
  },
  {
    Name: "Lionel Messi",
    Position: "Forward",
    DOB: "06/24/1987",
    ZodiacSign: "Cancer",
    JerseyNumber: "10",
    JerseyColor: "Blue",
    SuperstarStatus: "True",
    PlayerPicture:
      "https://thumbor.forbes.com/thumbor/fit-in/416x416/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F5ec595d45f39760007b05c07%2F0x0.jpg%3Fbackground%3D000000%26cropX1%3D989%26cropX2%3D2480%26cropY1%3D74%26cropY2%3D1564",
  },
  {
    Name: "Sergio Aguero",
    Position: "Forward",
    DOB: "06/02/1988",
    ZodiacSign: "Gemini",
    JerseyNumber: "19",
    JerseyColor: "Blue",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://www.mancity.com/meta/media/ekcdk54z/2019-sergio-aguero_1947.png",
  },
];

// 11 players for Team Brazil with respective key-value pairs

let Brazil = [
  {
    Name: "Alisson",
    Position: "Goalkeeper",
    DOB: "02/10/1992",
    ZodiacSign: "Libra",
    JerseyNumber: 1,
    JerseyColor: "Black",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/248681.jpg",
  },
  {
    Name: "Marcelo",
    Position: "Defender",
    DOB: "02/03/1990",
    ZodiacSign: "Pisces",
    JerseyNumber: 12,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/52947.jpg",
  },
  {
    Name: "Miranda",
    Position: "Defender",
    DOB: "13/12/1987",
    ZodiacSign: "Sagittarius",
    JerseyNumber: 3,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/37192.jpg",
  },
  {
    Name: "Thiago Silva",
    Position: "Defender",
    DOB: "22/09/1984",
    ZodiacSign: "Libra",
    JerseyNumber: 2,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/29391.jpg",
  },
  {
    Name: "Danilo",
    Position: "Midfielder",
    DOB: "15/06/1991",
    ZodiacSign: "Gemini",
    JerseyNumber: 14,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/168483.jpg",
  },
  {
    Name: "Paulinho",
    Position: "Midfielder",
    DOB: "25/07/1988",
    ZodiacSign: "Leo",
    JerseyNumber: 15,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/81998.jpg",
  },
  {
    Name: "Casemiro",
    Position: "Midfielder",
    DOB: "23/02/1992",
    ZodiacSign: "Pisces",
    JerseyNumber: 5,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/168874.jpg",
  },
  {
    Name: "Fernandinho",
    Position: "Midfielder",
    DOB: "04/05/1985",
    ZodiacSign: "Taurus",
    JerseyNumber: 17,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/37189.jpg",
  },
  {
    Name: "Neymar",
    Position: "Forward",
    DOB: "05/02/1992",
    ZodiacSign: "Aquarius",
    JerseyNumber: 10,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/142105.jpg",
  },
  {
    Name: "Gabriel Jesús",
    Position: "Forward",
    DOB: "30/08/1996",
    ZodiacSign: "Virgo",
    JerseyNumber: 9,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/307889.jpg",
  },
  {
    Name: "Coutinho",
    Position: "Forward",
    DOB: "12/06/1992",
    ZodiacSign: "Gemini",
    JerseyNumber: 11,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/120694.jpg",
  },
];

// 11 players for Spain with respective key-value pairs

let Spain = [
  {
    Name: "David de Gea",
    Position: "Goalkeeper",
    DOB: "11/07/1990",
    ZodiacSign: "Scorpio",
    JerseyNumber: "1",
    JerseyColor: "Red",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://upload.wikimedia.org/wikipedia/commons/6/68/David_de_Gea_2017.jpg",
  },
  {
    Name: "Jordi Alba",
    Position: "Defender",
    DOB: "03/21/1989",
    ZodiacSign: "Aries",
    JerseyNumber: "18",
    JerseyColor: "Red",
    SuperstarStatus: "True",
    PlayerPicture:
      "https://en.as.com/futbol/imagenes/2020/01/23/copa_del_rey/1579771260_194272_1579771436_noticia_normal.jpg",
  },
  {
    Name: "Sergio Ramos",
    Position: "Defender",
    DOB: "03/30/1986",
    ZodiacSign: "Aries",
    JerseyNumber: "15",
    JerseyColor: "Red",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://en.as.com/tikitakas/imagenes/2019/02/23/portada/1550919555_521513_1550919850_noticia_normal.jpg",
  },
  {
    Name: "Gerard Pique",
    Position: "Defender",
    DOB: "02/02/1987",
    ZodiacSign: "Aquarius",
    JerseyNumber: "3",
    JerseyColor: "Red",
    SuperstarStatus: "True",
    PlayerPicture:
      "https://icdn.football-espana.net/wp-content/uploads/2020/06/Pique-Sevilla.jpg",
  },
  {
    Name: "Dani Carvajal",
    Position: "Defender",
    DOB: "01/11/1992",
    ZodiacSign: "Capricorn",
    JerseyNumber: "2",
    JerseyColor: "Red",
    SuperstarStatus: "False",
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/191377.jpg",
  },
  {
    Name: "Andres Iniesta",
    Position: "Midfielder",
    DOB: "05/11/1984",
    ZodiacSign: "Taurus",
    JerseyNumber: "8",
    JerseyColor: "Red",
    SuperstarStatus: "True",
    PlayerPicture:
      "https://upload.wikimedia.org/wikipedia/commons/6/67/Andrés_Iniesta.jpg",
  },
  {
    Name: "Isco",
    Position: "Midfielder",
    DOB: "04/21/1992",
    ZodiacSign: "Taurus",
    JerseyNumber: "22",
    JerseyColor: "Red",
    SuperstarStatus: "False",
    PlayerPicture:
      "https://en.as.com/futbol/imagenes/2019/03/14/primera/1552554947_117211_1552555120_noticia_normal.jpg",
  },
  {
    Name: "Sergio Busquets",
    Position: "Midfielder",
    DOB: "07/16/1988",
    ZodiacSign: "Cancer",
    JerseyNumber: "5",
    JerseyColor: "Red",
    SuperstarStatus: "False",
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/124973.jpg",
  },
  {
    Name: "Thiago Silva",
    Position: "Midfielder",
    DOB: "09/22/1984",
    ZodiacSign: "Virgo",
    JerseyNumber: "2",
    JerseyColor: "Red",
    SuperstarStatus: "True",
    PlayerPicture:
      "https://en.as.com/en/imagenes/2020/05/10/football/1589115185_787877_noticia_normal.jpg",
  },
  {
    Name: "Koke",
    Position: "Midfielder",
    DOB: "01/08/1992",
    ZodiacSign: "Capricorn",
    JerseyNumber: "6",
    JerseyColor: "Red",
    SuperstarStatus: "False",
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/154352.jpg",
  },
  {
    Name: "Diego Costa",
    Position: "Attacker",
    DOB: "10/07/1988",
    ZodiacSign: "Libra",
    JerseyNumber: "19",
    JerseyColor: "Red",
    SuperstarStatus: "True",
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/73586.jpg",
  },
];

let teams = { Argentina, Brazil, Spain }; //Peru,

// export { Argentina, Brazil, Spain };

export default teams;
