// 11 players for Argentina with respecive key-values

let Argentina = [
  {
    Name: "Willy Caballero",
    Position: "Goalkeeper",
    DOB: "09/28/1981",
    ZodiacSign: "Libra",
    JerseyNumber: "13",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/17550.jpg",
  },
  {
    Name: "Nicolas Tagliafico",
    Position: "Defender",
    DOB: "08/31/1992",
    ZodiacSign: "Virgo",
    JerseyNumber: "3",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/169182.jpg",
  },
  {
    Name: "Federico Fazio",
    Position: "Defender",
    DOB: "03/17/1987",
    ZodiacSign: "Pisces",
    JerseyNumber: "20",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/73415.jpg",
  },
  {
    Name: "Nicolas Otamendi",
    Position: "Defender",
    DOB: "02/12/1988",
    ZodiacSign: "Aquarius",
    JerseyNumber: "17",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/114545.jpg",
  },
  {
    Name: "Gabriel Mercado",
    Position: "Defender",
    DOB: "03/18/1987",
    ZodiacSign: "Pisces",
    JerseyNumber: "25",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/86403.jpg",
  },
  {
    Name: "Angel Di Maria",
    Position: "Midfielder",
    DOB: "02/14/1988",
    ZodiacSign: "Aquarius",
    JerseyNumber: "11",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/43864.jpg",
  },
  {
    Name: "Javier Mascherano",
    Position: "Midfielder",
    DOB: "06/08/2984",
    ZodiacSign: "Gemini",
    JerseyNumber: "27",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/22185.jpg",
  },
  {
    Name: "Giovani Lo Celso",
    Position: "Midfielder",
    DOB: "04/09/1996",
    ZodiacSign: "Aries",
    JerseyNumber: "20",
    JerseyColor: "White",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/317683.jpg",
  },
  {
    Name: "Paulo Dybala",
    Position: "Midfielder",
    DOB: "11/15/1993",
    ZodiacSign: "Scorpio",
    JerseyNumber: "21",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/205118.jpg",
  },
  {
    Name: "Lionel Messi",
    Position: "Forward",
    DOB: "06/24/1987",
    ZodiacSign: "Cancer",
    JerseyNumber: "10",
    JerseyColor: "Blue",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/26622.jpg",
  },
  {
    Name: "Sergio Aguero",
    Position: "Forward",
    DOB: "06/02/1988",
    ZodiacSign: "Gemini",
    JerseyNumber: "19",
    JerseyColor: "Blue",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/43370.jpg",
  },
];

// 11 players for Team Brazil with respective key-value pairs

let Brazil = [
  {
    Name: "Alisson",
    Position: "Goalkeeper",
    DOB: "02/10/1992",
    ZodiacSign: "Libra",
    JerseyNumber: 1,
    JerseyColor: "Black",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/248681.jpg",
  },
  {
    Name: "Marcelo",
    Position: "Defender",
    DOB: "02/03/1990",
    ZodiacSign: "Pisces",
    JerseyNumber: 12,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/52947.jpg",
  },
  {
    Name: "Miranda",
    Position: "Defender",
    DOB: "13/12/1987",
    ZodiacSign: "Sagittarius",
    JerseyNumber: 3,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/37192.jpg",
  },
  {
    Name: "Thiago Silva",
    Position: "Defender",
    DOB: "22/09/1984",
    ZodiacSign: "Libra",
    JerseyNumber: 2,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/29391.jpg",
  },
  {
    Name: "Danilo",
    Position: "Midfielder",
    DOB: "15/06/1991",
    ZodiacSign: "Gemini",
    JerseyNumber: 14,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/168483.jpg",
  },
  {
    Name: "Paulinho",
    Position: "Midfielder",
    DOB: "25/07/1988",
    ZodiacSign: "Leo",
    JerseyNumber: 15,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/81998.jpg",
  },
  {
    Name: "Casemiro",
    Position: "Midfielder",
    DOB: "23/02/1992",
    ZodiacSign: "Pisces",
    JerseyNumber: 5,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/168874.jpg",
  },
  {
    Name: "Fernandinho",
    Position: "Midfielder",
    DOB: "04/05/1985",
    ZodiacSign: "Taurus",
    JerseyNumber: 17,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/37189.jpg",
  },
  {
    Name: "Neymar",
    Position: "Forward",
    DOB: "05/02/1992",
    ZodiacSign: "Aquarius",
    JerseyNumber: 10,
    JerseyColor: "Yellow",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/142105.jpg",
  },
  {
    Name: "Gabriel Jesús",
    Position: "Forward",
    DOB: "30/08/1996",
    ZodiacSign: "Virgo",
    JerseyNumber: 9,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/307889.jpg",
  },
  {
    Name: "Coutinho",
    Position: "Forward",
    DOB: "12/06/1992",
    ZodiacSign: "Gemini",
    JerseyNumber: 11,
    JerseyColor: "Yellow",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/120694.jpg",
  },
];

// 11 players for Spain with respective key-value pairs

let Spain = [
  {
    Name: "David de Gea",
    Position: "Goalkeeper",
    DOB: "11/07/1990",
    ZodiacSign: "Scorpio",
    JerseyNumber: "1",
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/148647.jpg",
  },
  {
    Name: "Jordi Alba",
    Position: "Defender",
    DOB: "03/21/1989",
    ZodiacSign: "Aries",
    JerseyNumber: "18",
    JerseyColor: "Red",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/125417.jpg",
  },
  {
    Name: "Sergio Ramos",
    Position: "Defender",
    DOB: "03/30/1986",
    ZodiacSign: "Aries",
    JerseyNumber: "15",
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/19198.jpg",
  },
  {
    Name: "Gerard Pique",
    Position: "Defender",
    DOB: "02/02/1987",
    ZodiacSign: "Aquarius",
    JerseyNumber: "3",
    JerseyColor: "Red",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/27798.jpg",
  },
  {
    Name: "Dani Carvajal",
    Position: "Defender",
    DOB: "01/11/1992",
    ZodiacSign: "Capricorn",
    JerseyNumber: "2",
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/191377.jpg",
  },
  {
    Name: "Andres Iniesta",
    Position: "Midfielder",
    DOB: "05/11/1984",
    ZodiacSign: "Taurus",
    JerseyNumber: "8",
    JerseyColor: "Red",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/5057.jpg",
  },
  {
    Name: "Isco",
    Position: "Midfielder",
    DOB: "04/21/1992",
    ZodiacSign: "Taurus",
    JerseyNumber: "22",
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/177605.jpg",
  },
  {
    Name: "Sergio Busquets",
    Position: "Midfielder",
    DOB: "07/16/1988",
    ZodiacSign: "Cancer",
    JerseyNumber: "5",
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/124973.jpg",
  },
  {
    Name: "Thiago",
    Position: "Midfielder",
    DOB: "04/11/1991",
    ZodiacSign: "Aries",
    JerseyNumber: "10",
    JerseyColor: "Red",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/142540.jpg",
  },
  {
    Name: "Koke",
    Position: "Midfielder",
    DOB: "01/08/1992",
    ZodiacSign: "Capricorn",
    JerseyNumber: "6",
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/154352.jpg",
  },
  {
    Name: "Diego Costa",
    Position: "Attacker",
    DOB: "10/07/1988",
    ZodiacSign: "Libra",
    JerseyNumber: "19",
    JerseyColor: "Red",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/73586.jpg",
  },
];

let Peru = [
  {
    Name: "Pedro Gallese",
    Position: "Goalkeeper",
    DOB: "23/02/1990",
    ZodiacSign: "Pisces",
    JerseyNumber: 1,
    JerseyColor: "Black",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/165083.jpg",
  },
  {
    Name: "Luis Advincula",
    Position: "Defender",
    DOB: "02/03/1990",
    ZodiacSign: "Pisces",
    JerseyNumber: 17,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/138247.jpg",
  },
  {
    Name: "Anderson Santamaria",
    Position: "Defender",
    DOB: "01/10/1992",
    ZodiacSign: "Capricorn",
    JerseyNumber: 4,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/179350.jpg",
  },
  {
    Name: "Christian Ramos",
    Position: "Defender",
    DOB: "11/04/1988",
    ZodiacSign: "Scorpio",
    JerseyNumber: 15,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/132239.jpg",
  },
  {
    Name: "Miguel Trauco",
    Position: "Defender",
    DOB: "08/25/1992",
    ZodiacSign: "Virgo",
    JerseyNumber: 6,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/180812.jpg",
  },
  {
    Name: "Pedro Aquino",
    Position: "Midfielder",
    DOB: "04/13/1995",
    ZodiacSign: "Aries",
    JerseyNumber: 23,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/231218.jpg",
  },
  {
    Name: "Yoshimar Yotun",
    Position: "Midfielder",
    DOB: "04/07/1990",
    ZodiacSign: "Aries",
    JerseyNumber: 19,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/132124.jpg",
  },
  {
    Name: "Andre Carrillo",
    Position: "Midfielder",
    DOB: "06/14/1991",
    ZodiacSign: "Gemini",
    JerseyNumber: 18,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/165090.jpg",
  },
  {
    Name: "Christian Cueva",
    Position: "Midfielder",
    DOB: "11/23/1991",
    ZodiacSign: "Sagittarius",
    JerseyNumber: 8,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/132284.jpg",
  },
  {
    Name: "Edison Flores",
    Position: "Midfielder",
    DOB: "05/14/1994",
    ZodiacSign: "Taurus",
    JerseyNumber: 20,
    JerseyColor: "Red",
    SuperstarStatus: false,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/188673.jpg",
  },
  {
    Name: "Paolo Guerrero",
    Position: "Forward",
    DOB: "01/01/1984",
    ZodiacSign: "Capricorn",
    JerseyNumber: 20,
    JerseyColor: "Red",
    SuperstarStatus: true,
    PlayerPicture: "https://s.hs-data.com/bilder/spieler/gross/8953.jpg",
  },
];

const teams = { Argentina, Brazil, Spain, Peru };

export default teams
